# Escreva o scrip abaixo e salve como makefile<sem formato>
# No terminal faça:
# all:
# [tab]gcc main.c funcao.c defs.h protos.h -o programa.exe
# Depois faça em linha de comando:
# ~:$ mingw32-make --always-make
all:
	gcc vice.c defs.h -o programa.exe
