# Escreva o scrip abaixo e salve como makefile<sem formato>
# No terminal faça:
# all:
# [tab]gcc main.c funcao.c defs.h protos.h -o programa.exe
# Depois faça em linha de comando:
# ~:$ mingw32-make
# Será executada o makefile existente.
all:
	gcc main.c funcao.c proto.h -o programa.exe
